/**
 * AUTO-GENERATED by `scripts/generate-deployments.mjs` — do not edit by hand.
 *
 * Regenerate with `pnpm --filter @aftermarket/session-oracle run gen:deployments`,
 * which also runs automatically before `build`, `typecheck` and `test`.
 *
 * Source: `contracts/deployments/<chainId>.json`, one file per chain — see `src/deployments.ts`
 * for the schema and the typed registry API built on top of this data.
 */

/**
 * Mirrors `DeployedMarket` in `./deployments.ts`. Duplicated here (rather than
 * imported) so this generated file has no dependency on hand-written source — the generator
 * only ever needs to emit data shaped like this interface, never to import TypeScript logic.
 */
interface GeneratedMarket {
  name: string;
  oracle: `0x${string}`;
  collateralToken: `0x${string}`;
  loanToken: `0x${string}`;
  calendar: `0x${string}`;
  feed: `0x${string}`;
  pool: `0x${string}`;
}

export const DEPLOYMENTS_BY_CHAIN: Readonly<Record<number, readonly GeneratedMarket[]>> = {};
